name: Linter and Tester
on:
  push:
  pull_request:

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v1
      - name: Prepare
        run: npm ci
      - name: Lint
        uses: mooyoul/tslint-actions@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '*.ts'
  test:
    name: 'Node.js v${{ matrix.node }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 16
          - 18
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node }}'
      - uses: actions/checkout@v2
      - name: 'Cache node_modules'
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v${{ matrix.node }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v${{ matrix.node }}-
      - name: Install Dependencies
        run: yarn install
      - name: Run All Node.js Tests
        run: yarn test
Footer
